version: '3'

services:
  back:
    image: sitn/infolica-back
    build:
      context: back
      args:
        BACK_INI_FILE: ${BACK_INI_FILE}
    command: "gunicorn wsgi --preload -b :8000 --worker-class=gthread --threads=10 --workers=4 --timeout=60 --max-requests=1000"
    restart: unless-stopped
    ports:
      - "${DOCKER_BACK_PORT}:8000"
    volumes:
      - "${AFFAIRES_PATH}:/mnt/affaires_conservation:rw"
      - "${TEMPLATES_PATH}:/mnt/infolica_templates:ro"
      - "${TEMP_PATH}:/mnt/infolica_temp:rw"
    env_file: .env

  front:
    image: sitn/infolica-front
    build:
      context: front
      args:
        INSTANCE: ${INSTANCE}
        PUBLIC_PATH: ${PUBLIC_PATH}
        API_URL: ${API_URL}
    restart: unless-stopped
    ports:
      - "${DOCKER_FRONT_PORT}:80"
